version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@kpi.ua
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://untitled9_db_1:5432/postgres -schemas=public -user=postgres -password=postgres -baselineOnMigrate=true migrate
    volumes:
    - .:/flyway/sql
volumes:
    postgres:
    pgadmin:
    flyway:

